from sympy import Symbol, Function

__all__ = [
    "DUMMY",
    "READ",
    "WRITE",
    "ATOMIC_ADD",
    "GROUPS",
    "PEAK_FLOPS",
    "BANDWIDTH",
    "MIN_MMA_EFFICIENCY",
    "FWD_CONTENTION",
    "BWD_CONTENTION",
    "SM_COUNT",
    "MAX_PROGRAMS_PER_SM",
    "SMEM_PER_SM",
]

DUMMY = Symbol('DUMMY')
READ = Symbol('READ')
WRITE = Symbol('WRITE')
ATOMIC_ADD = Symbol('ATOMIC_ADD')
GROUPS = Symbol('GROUPS')
PEAK_FLOPS = Symbol('PEAK_FLOPS')
BANDWIDTH = Symbol('BANDWIDTH')
MIN_MMA_EFFICIENCY = Symbol('MIN_MMA_EFFICIENCY')
SM_COUNT = Symbol('SM_COUNT')
MAX_PROGRAMS_PER_SM = Symbol('MAX_PROGRAMS_PER_SM')
SMEM_PER_SM = Symbol('SMEM_PER_SM')
FWD_CONTENTION = Function('FWD_CONTENTION')
BWD_CONTENTION = Function('BWD_CONTENTION')
